server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment-consul-8004

# 配置consul
  cloud:
    consul:
      host: 192.168.26.144
      port: 8500
      discovery:
        service-name: ${spring.application.name}
