#子模块端口号
server:
  port: 8001

#子模块名称
spring:
  application:
    name: cloud-provider-server
  #    mysql配置信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: xu.123456

#    mybatis映射文件地址和pojo路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xha.springcloud.pojo

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #主机名称
    instance-id: cloud-provider-server-8001
    #显示ip地址
    prefer-ip-address: true
#    Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
#      Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认为30s）
    lease-renewal-interval-in-seconds: 1
