server:
  port: 3344
spring:
  application:
    name: cloud-config-centre
  cloud:
    config:
      server:
        git:
          #          gitee仓库地址
          uri: https://gitee.com/xu-huaiang/springcloud-config-center.git
          #          用户名
          username: 13783239983
          #          密码
          password: xuhuaiang123
          #          指定分支
        default-label: master
#        rabbitmq的相关配置
  rabbitmq:
    host: 192.168.26.142
    port: 5672
    username: guest
    password: guest
#    暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'busrefresh'




eureka:
  instance:
    prefer-ip-address: true
    instance-id: cloud-config-centre-3344
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka



